### ISSUE TITLE
Add options to allow defining the env file and the example file to look for

### ISSUE THREAD

**Issue by micalevisk** [arvindell/envful#3]
I think would be great if we could customize the following two values

https://github.com/arvindell/envful/blob/7771ea94f9c678fb9c241d0594e973073979fa77/src/checker.rs#L12-L13

my use case: I have multiple .env files, one for each environment like `.development.env` &  `.development.env.example`. Thus, I cannot use this cool tool :disappointed: 

my proposal: `--example <path/to/.env.example>` and `--path <path/to/.env>`

**Comment by arvindell** [comment]
Thanks for the suggestion. I've thought about this previously and agree those flags are needed. 

I will see if I can get it done before the end of february!

**Comment by micalevisk** [comment]
nice

```bash
$ envful -f ./env/.development.env -m ./env/.development.env.example check
Checking environment...
All variables are present ✅

# after removing a mandatory one
$ envful -f ./env/.development.env -m ./env/.development.env.example check
Checking environment...
The process is missing required environment variables:
❌ Missing variable: NODE_ENV
```

**Comment by arvindell** [comment]
Thanks for the early test! Just pushed a minor patch in 1.0.1 btw
